[Interface]
Address = 10.99.50.8
PrivateKey = mLn2MQ/tcm7q0QTTtIPoVhWwKB+kcjNKmHmo7+YrhF0=
ListenPort = 51820
DNS = 8.8.8.8

[Peer]
PublicKey = OhTx2HlyTZvHuNYt9k/yxsuWLYeXC8wag9PMAEJ/NwA=
PresharedKey = OWQa0rjrSQA6sDubJ7luBtec3ZDI+CB4peCeoRrRawI=
Endpoint = 192.168.1.14:51820
AllowedIPs = 10.10.0.0/24
