[Interface]
Address = 10.99.50.11
PrivateKey = aIDG7CIOR8yTYl60JzDGLqoDjV0KxFrlV2MyBi5I10M=
ListenPort = 51820
DNS = 8.8.8.8

[Peer]
PublicKey = OhTx2HlyTZvHuNYt9k/yxsuWLYeXC8wag9PMAEJ/NwA=
PresharedKey = rGVLRTjN3GJIggOFMxUe1st1VLMnpjx3ws8rk88RuG8=
Endpoint = 192.168.1.14:51820
AllowedIPs = 10.10.0.0/24
