[Interface]
Address = 10.99.50.4
PrivateKey = SDmhAONpT7fcJ5NaKXmztmnDdX3jt3R9gWWKc2Af7EQ=
ListenPort = 51820
DNS = 8.8.8.8

[Peer]
PublicKey = OhTx2HlyTZvHuNYt9k/yxsuWLYeXC8wag9PMAEJ/NwA=
PresharedKey = glCrb49h9++D36hoIeAyRMPeCt3uP7mXh/PkvR/gVbA=
Endpoint = 192.168.1.14:51820
AllowedIPs = 10.10.0.0/24
