[Interface]
Address = 10.99.50.1
ListenPort = 51820
PrivateKey = QOXQsgDnZ9Cj7l75c1PUHOSK2GuchuVhQdGbnl9ylFw=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer1
PublicKey = rg8fbSCTHVbmAlFnXUjB9tAwroKtpwxj+y5m07erNHE=
PresharedKey = ohrC07TZubqBSJwSMt2JLkb7MYxYmzCHzQnmMqa8EmE=
AllowedIPs = 10.99.50.2/32

[Peer]
# peer2
PublicKey = 7yvrJOZU+7bMddXW3YrHSFftGvXv0GqTVLA2nCzDRmM=
PresharedKey = QwH7MJ1Yh8JS5itrqOAak5KpXADEVGaEJ6iWUQEVioA=
AllowedIPs = 10.99.50.3/32

[Peer]
# peer3
PublicKey = KS7ojtURjayXACOUca3gLm2BBYXFuNNU92+shXPNmXg=
PresharedKey = glCrb49h9++D36hoIeAyRMPeCt3uP7mXh/PkvR/gVbA=
AllowedIPs = 10.99.50.4/32

[Peer]
# peer4
PublicKey = CdGcTN98WVMj7aP9G44IZtWWbg9ZNccXMswzwkBqvlU=
PresharedKey = Up+UCEENSNdkJWsvdgdtP/CRojhg1pFFXxdoO29s74g=
AllowedIPs = 10.99.50.5/32

[Peer]
# peer5
PublicKey = U4/NgKH4nXyFdGTEqIZwjo3Wxmx4/eMEqdNNvuwkOlA=
PresharedKey = fLaxfkjDBXmtpDqmhWsb9tflQohR7t2F3UA7OL2o4TM=
AllowedIPs = 10.99.50.6/32

[Peer]
# peer6
PublicKey = QI8K5VBmBF4X8m9pwUhEV+/cG0OZfrSHKLPFkZlyRDc=
PresharedKey = Z5wwKukbiT3hCCPEleMyxqI1sx9v9FjTRrunt+Obb4M=
AllowedIPs = 10.99.50.7/32

[Peer]
# peer7
PublicKey = 7cenZUNZUD9ohTlHGRXwBNiT1+y7FTNiOT9UWN0HgQ4=
PresharedKey = OWQa0rjrSQA6sDubJ7luBtec3ZDI+CB4peCeoRrRawI=
AllowedIPs = 10.99.50.8/32

[Peer]
# peer8
PublicKey = 35BjDU7CHprRSvO6sPk3IFeSQLSCMQGdiiOou8Fo1C4=
PresharedKey = y9MQ7Zub/cQY2uqcIoiyF/KAQ+0z2WX/ZGe3aVqGqRQ=
AllowedIPs = 10.99.50.9/32

[Peer]
# peer9
PublicKey = nwQMA7kU40ZwiR7javBeXCUq4+1ciBx8gr0n4NpaWHk=
PresharedKey = B6g217QIFXDE2vjMs34XN2++u0xPYY8P4i4Vr3pm09Y=
AllowedIPs = 10.99.50.10/32

[Peer]
# peer10
PublicKey = 7lJS9UUHK3ccXpomaOfFacGID0jSt9MKmqgquxY820E=
PresharedKey = rGVLRTjN3GJIggOFMxUe1st1VLMnpjx3ws8rk88RuG8=
AllowedIPs = 10.99.50.11/32

