[Interface]
Address = 10.99.50.3
PrivateKey = sLftiV/eYMr0Fy9jUudzSpv4Qnew6h+4yExl0amMZFU=
ListenPort = 51820
DNS = 8.8.8.8

[Peer]
PublicKey = OhTx2HlyTZvHuNYt9k/yxsuWLYeXC8wag9PMAEJ/NwA=
PresharedKey = QwH7MJ1Yh8JS5itrqOAak5KpXADEVGaEJ6iWUQEVioA=
Endpoint = 192.168.1.14:51820
AllowedIPs = 10.10.0.0/24
