[Interface]
Address = 10.99.50.9
PrivateKey = UKNqN/MQ5mgF3qsQ7c3skX4DUgNXoSTLw5TblfBJT3g=
ListenPort = 51820
DNS = 8.8.8.8

[Peer]
PublicKey = OhTx2HlyTZvHuNYt9k/yxsuWLYeXC8wag9PMAEJ/NwA=
PresharedKey = y9MQ7Zub/cQY2uqcIoiyF/KAQ+0z2WX/ZGe3aVqGqRQ=
Endpoint = 192.168.1.14:51820
AllowedIPs = 10.10.0.0/24
