[Interface]
Address = 10.99.50.7
PrivateKey = EAzHgNTBP27cpDVLLfOQhkPlBH6zzaVa9dCGH5KSiE4=
DNS = 8.8.8.8

[Peer]
PublicKey = OhTx2HlyTZvHuNYt9k/yxsuWLYeXC8wag9PMAEJ/NwA=
PresharedKey = Z5wwKukbiT3hCCPEleMyxqI1sx9v9FjTRrunt+Obb4M=
Endpoint = 192.168.1.14:51820
AllowedIPs = 10.10.0.0/24
