CREATE TABLE IF NOT EXISTS admin_user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS game_config (
  id INT AUTO_INCREMENT PRIMARY KEY,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  tick_length INT NOT NULL,
  num_ticks INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS team (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  name VARCHAR(120) NOT NULL UNIQUE,
  ip_address VARCHAR(64) NOT NULL UNIQUE,
  api_token VARCHAR(64) NOT NULL UNIQUE,
  ssh_private_key TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS team_credential (
  id INT AUTO_INCREMENT PRIMARY KEY,
  team_id INT NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  password_plain VARCHAR(64) NOT NULL,
  CONSTRAINT fk_team_credential_team FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS challenge (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  name VARCHAR(120) NOT NULL UNIQUE,
  port INT NOT NULL,
  sla_script VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS flag_access_token (
  id INT AUTO_INCREMENT PRIMARY KEY,
  team_id INT NOT NULL,
  challenge_id INT NOT NULL,
  token VARCHAR(64) NOT NULL UNIQUE,
  CONSTRAINT uq_flag_access_token UNIQUE (team_id, challenge_id),
  CONSTRAINT fk_flag_token_team FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE,
  CONSTRAINT fk_flag_token_challenge FOREIGN KEY (challenge_id) REFERENCES challenge(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS flag (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  value VARCHAR(255) NOT NULL UNIQUE,
  team_id INT NOT NULL,
  challenge_id INT NOT NULL,
  CONSTRAINT fk_flag_team FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE,
  CONSTRAINT fk_flag_challenge FOREIGN KEY (challenge_id) REFERENCES challenge(id) ON DELETE CASCADE,
  UNIQUE KEY uniq_flag_team_challenge (team_id, challenge_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS flag_submission (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  attacker_id INT NOT NULL,
  defender_id INT NULL,
  challenge_id INT NULL,
  submitted_flag VARCHAR(255) NOT NULL,
  is_valid TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT fk_submission_attacker FOREIGN KEY (attacker_id) REFERENCES team(id) ON DELETE CASCADE,
  CONSTRAINT fk_submission_defender FOREIGN KEY (defender_id) REFERENCES team(id) ON DELETE SET NULL,
  CONSTRAINT fk_submission_challenge FOREIGN KEY (challenge_id) REFERENCES challenge(id) ON DELETE SET NULL,
  INDEX idx_submission_created_at (created_at),
  INDEX idx_submission_valid (is_valid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sla_result (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  team_id INT NOT NULL,
  challenge_id INT NOT NULL,
  passed TINYINT(1) NOT NULL DEFAULT 0,
  tick_number INT NOT NULL,
  CONSTRAINT fk_sla_team FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE,
  CONSTRAINT fk_sla_challenge FOREIGN KEY (challenge_id) REFERENCES challenge(id) ON DELETE CASCADE,
  INDEX idx_sla_tick (tick_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
