[Interface]
Address = 10.99.50.10
PrivateKey = OMlKot5rlgHjUx42Nhpyvmdg3jS9yHNNQsnC1jphZ1g=
ListenPort = 51820
DNS = 8.8.8.8

[Peer]
PublicKey = OhTx2HlyTZvHuNYt9k/yxsuWLYeXC8wag9PMAEJ/NwA=
PresharedKey = B6g217QIFXDE2vjMs34XN2++u0xPYY8P4i4Vr3pm09Y=
Endpoint = 192.168.1.14:51820
AllowedIPs = 10.10.0.0/24
