[Interface]
Address = 10.99.50.6
PrivateKey = iKp3UWoOkG2lynz9q56l5taDaAIO3Sv9fW0vzGAUxWE=
ListenPort = 51820
DNS = 8.8.8.8

[Peer]
PublicKey = OhTx2HlyTZvHuNYt9k/yxsuWLYeXC8wag9PMAEJ/NwA=
PresharedKey = fLaxfkjDBXmtpDqmhWsb9tflQohR7t2F3UA7OL2o4TM=
Endpoint = 192.168.1.14:51820
AllowedIPs = 10.10.0.0/24
