[Interface]
Address = 10.99.50.5
PrivateKey = cNAlFAT60Oscf+sRjypvvsFJMCIdVWtmM1cH4ak172c=
ListenPort = 51820
DNS = 8.8.8.8

[Peer]
PublicKey = OhTx2HlyTZvHuNYt9k/yxsuWLYeXC8wag9PMAEJ/NwA=
PresharedKey = Up+UCEENSNdkJWsvdgdtP/CRojhg1pFFXxdoO29s74g=
Endpoint = 192.168.1.14:51820
AllowedIPs = 10.10.0.0/24
